### ISSUE TITLE
`bm_pixmap()`

### ISSUE THREAD

**Issue by trevorld** [trevorld/bittermelon#60]
# ToDo

* [x] `bm_pixmap()`, `as_bm_pixmap()`, `is_bm_pixmap()`
* [x] `format()` and `print()`
* [x] `as.matrix()`
* [x] `farming_crops_16x16()` sprites
* [x] `as_bm_bitmap.bm_pixmap()` and use it in `print.bm_pixmap()` when `cli::ansi_num_colors() == 1L`
* [ ] #69
* [x] `Ops`?
* [ ] `c()`
* [x] `cbind()` and `rbind()`
* [x] `bm_clamp()`
* [x] `bm_distort()`
* [x] `bm_expand()`
* [x]  `bm_extend()`
* [x] `bm_flip()`
* [x] `bm_mask()`
* [x] `bm_outline()`
* [x] `bm_overlay()`
* [x] `bm_pad()`
* [x] `bm_resize()`
* [x] `bm_rotate()`
* [x] `bm_shadow()`, `bm_bold()`, `bm_glow()`
* [x]  `bm_trim()`
* [x] `bm_widths()` and `bm_heights()`
* [x] `as.array.bm_pixmap()` (for writing with `png::writePNG()` and friends)
* [ ] #70
* [x] `bm_expand()`'s `height` should now default to `width`
* [ ] #71
* [x] Update examples
* [x] Update return values
* [x] Update parameters

# Original comment

* `print.bm_bitmap()` compression options are better optimized for printing binary bitmaps where the terminal may or may not support color or unicode glyphs and we want to have fun with customizable Unicode glyphs...
* Sometimes would be nice though for a print method optimized for use case where each value is considered a colored pixel and we assume support for both color and relevant box glyphs
* Support basic "horizontal" and "vertical" "compression" schemes
* For basic "both" compression what to do if we need more than two colors?
* Go beyond binary compression?
* Functions to convert colors to {cli} palette values?
* Convert NA's to default terminal background color?
* Better name?

**Comment by trevorld** [comment]
Or maybe create a `"bm_raster"` subclass of the raster class with a `print.bm_raster()` method?

**Comment by trevorld** [comment]
Some example programs that do something similar:

* https://github.com/matrach/img2unicode?tab=readme-ov-file
* https://github.com/eliukblau/pixterm
* https://github.com/lbenedetto/Image2Terminal
* https://github.com/kevinpt/UnicodeImage

**Comment by trevorld** [comment]
Would be fun to do an example with sprites: https://coolbutuseless.github.io/2018/08/13/gganimate-with-sprites/

**Comment by trevorld** [comment]
* `bm_raster` objects could by supported by other `{bittermelon}` methods such as `bm_flip()` etc.
* Default padding could be `NA_character_`?

**Comment by trevorld** [comment]
Better to use ""#FFFFFF00"" to represent fully transparent values (which matches `col2rgb("transparent", alpha=TRUE)`) or `"#00000000"` (which matches a "nativeRaster"'s `0` integer value)?

**Comment by trevorld** [comment]
Would be cool to also support `{pixeltrix}` sprites as well: https://github.com/matt-dray/pixeltrix/issues/36
